version: "3.3"
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    volumes:
     - ./.docker/nginx/config:/etc/nginx/conf.d:ro
     - ./.docker/nginx/log/:/var/log/nginx:rw
     - .:/var/www/html:rw
    depends_on:
     - php
    ports:
     - ${NGINX_PORT}:80
    networks:
     - default

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - .docker/php/log/php:/var/log/php:rw
      - .:/var/www/html:rw
    ports:
      - "9000:9000"
    networks:
     - default

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis
    volumes:
      - ./.docker/redis/data:/data:rw
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default